### ISSUE TITLE
I need database file

### ISSUE THREAD

**Issue by hogwart120** [blackphreak/Feather_Server#21]

**Comment by blackphreak** [comment]
Thanks for being interested in this project.

Here you go:
[feather.sql.empty.zip](https://github.com/blackphreak/Feather_Server/files/5721009/feather.sql.empty.zip)
.
btw, this server code has been abandoned a long time ago.
I'm working on a new design of the game server by implementing "event-driven system".
If you are interested in it, please leave any contact method here, so I can contact you later on.

**Comment by hogwart120** [comment]
you can share me folder www of localhost

**Comment by hogwart120** [comment]
msi.official.vn@gmail.com you can contact  to me. Thanks
